"""Hằng số nghiệp vụ cho rulebase ngân sách."""

NEEDS_RATIO = 0.50
WANTS_RATIO = 0.30
SAVINGS_RATIO = 0.20

LOW_SAVINGS_RATE = 0.10
TARGET_SAVINGS_RATE = 0.20
HIGH_DEBT_PAYMENT_RATIO = 0.20
HIGH_FIXED_EXPENSE_RATIO = 0.50
TIGHT_GOAL_SURPLUS_USAGE = 0.80

EMERGENCY_FUND_MONTHS_STABLE = 3
EMERGENCY_FUND_MONTHS_UNSTABLE = 6
